// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCehFWnBPaBQGmpIj5Xh8AOwP3VoL1j1ZU',
    appId: '1:903387433194:web:60ebf94f3dfbafa2a5af93',
    messagingSenderId: '903387433194',
    projectId: 'billing-system-shansau',
    authDomain: 'billing-system-shansau.firebaseapp.com',
    storageBucket: 'billing-system-shansau.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD3CZUDfX2sDuv7CDMpWvJqoQzOf6L6RA',
    appId: '1:903387433194:android:e4824a04ae05c041a5af93',
    messagingSenderId: '903387433194',
    projectId: 'billing-system-shansau',
    storageBucket: 'billing-system-shansau.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7oZum10ru-Vcw0zGuiYq0dvLUVHLzFm0',
    appId: '1:903387433194:ios:6af77ff0e3a5d695a5af93',
    messagingSenderId: '903387433194',
    projectId: 'billing-system-shansau',
    storageBucket: 'billing-system-shansau.appspot.com',
    iosBundleId: 'com.example.billingSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7oZum10ru-Vcw0zGuiYq0dvLUVHLzFm0',
    appId: '1:903387433194:ios:66cc604830c9e83ea5af93',
    messagingSenderId: '903387433194',
    projectId: 'billing-system-shansau',
    storageBucket: 'billing-system-shansau.appspot.com',
    iosBundleId: 'com.example.billingSystem.RunnerTests',
  );
}
